# Generated by Django 3.2.8 on 2022-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('operations_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=80)),
                ('client_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=600, null=True, verbose_name='Production Status')),
                ('finish_detail', models.CharField(max_length=100, null=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Operations',
                'verbose_name_plural': 'Operations',
            },
        ),
    ]
