# Generated by Django 3.2.8 on 2022-01-27 20:38

from django.db import migrations, models
import ms_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=20, validators=[ms_app.validators.validate_project_code])),
                ('project_name', models.CharField(max_length=80)),
                ('client_name', models.CharField(max_length=100)),
                ('project_detail', models.CharField(max_length=600, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[ms_app.validators.validate_value])),
                ('currency', models.CharField(choices=[('MYR', 'RM'), ('EUR', '€'), ('USD', '$'), ('SGD', 'SGD')], default='MYR', max_length=5)),
                ('order_date', models.DateField(null=True, verbose_name='Customer Order Date')),
                ('shipping_date', models.CharField(max_length=100, null=True, verbose_name='Customer Working Date')),
                ('payment_term', models.CharField(max_length=100, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
