# Generated by Django 3.2.8 on 2022-01-27 20:43

import datetime
from django.db import migrations, models
import ms_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='client_name',
            field=models.CharField(max_length=100, validators=[ms_app.validators.check_null]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='order_date',
            field=models.DateField(default=datetime.datetime(1950, 1, 1, 0, 0), verbose_name='Customer Order Date'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_term',
            field=models.CharField(default='null', max_length=100, validators=[ms_app.validators.check_null]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='project_detail',
            field=models.CharField(default='null', max_length=600, validators=[ms_app.validators.check_null]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='project_name',
            field=models.CharField(max_length=80, validators=[ms_app.validators.check_null]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='shipping_date',
            field=models.CharField(default='null', max_length=100, validators=[ms_app.validators.check_null], verbose_name='Customer Working Date'),
        ),
    ]
