# Generated by Django 3.2.8 on 2022-01-28 00:02

from django.db import migrations, models
import purchases_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_app', '0002_auto_20220127_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[purchases_app.validators.validate_value]),
        ),
    ]
