# Generated by Django 3.2.8 on 2022-01-27 21:06

from django.db import migrations, models
import ms_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='invoice_number',
            field=models.CharField(max_length=30, validators=[ms_app.validators.check_null]),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(max_length=100, validators=[ms_app.validators.check_null]),
        ),
    ]
