# Generated by Django 3.2.8 on 2022-01-27 21:08

import datetime
from django.db import migrations, models
import ms_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_auto_20220127_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(1950, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='invoice_number',
            field=models.CharField(max_length=30, null=True, validators=[ms_app.validators.check_null]),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(max_length=200, null=True, validators=[ms_app.validators.check_null]),
        ),
    ]
