# Generated by Django 3.2.8 on 2022-01-27 22:06

from django.db import migrations, models
import ms_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_auto_20220127_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='invoice_number',
            field=models.CharField(default='null', max_length=100, null=True, validators=[ms_app.validators.check_null]),
        ),
    ]
