# Generated by Django 3.2.8 on 2022-01-27 20:38

from django.db import migrations, models
import ms_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shipping_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=20, validators=[ms_app.validators.validate_project_code])),
                ('project_name', models.CharField(max_length=80, null=True)),
                ('client_name', models.CharField(max_length=100)),
                ('germany', models.CharField(max_length=500, null=True)),
                ('customer', models.CharField(max_length=500, null=True)),
                ('charges', models.CharField(max_length=100, null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shipping',
            },
        ),
    ]
